### ISSUE TITLE
How to validate oracle price before injecting into the protocol, what is the best practice?

### ISSUE THREAD

**Issue by adagora** [Cyfrin/foundry-defi-stablecoin-f23#40]
### Hi all,
fantastic course! @PatrickAlphaC, I'm interested in hearing your viewpoints and assessing the value of implementing the following practices to create a robust oracle:

## **Oracle Design Requirements:**
1. Double-check chainlink price data against other sources,
2. Wait for validation if price is correct,
3. Fallback e.g falling back to the Tellor ETH:USD oracle under the following (extreme) conditions (no access 3~ 4h to chainlink oracle),
4. Maybe some ML to predict anomaly/analyzing fluctuation/analyzing and forecasting based on chainlink historical price data, (see below point 6.)

##  **Why**
 do not assume chainlink is always correct (e.g multisig can be compromised)

## Additionally, I came across the [PriceFeed from Liquidity protocol](https://etherscan.io/address/0x4c517d4e2c851ca76d7ec94b805269df0f2201de#code) with properties:
5. 4h, Maximum time period allowed since Chainlink's latest round data timestamp, beyond which Chainlink is considered frozen.
6. 50%, // Maximum deviation allowed between two consecutive Chainlink oracle prices. 18-digit precision.
7. The last good price seen from an oracle by Liquity.
8. fallback to tellor oracle

Your thoughts on whether these practices are worth implementing would be highly valuable

**Comment by PatrickAlphaC** [comment]
> Double-check chainlink price data against other sources

So... this is already what makes Chainlink so great, Chainlink is a network of nodes that all get data from different sources! 

Now if you're talking about comparing Chainlink against other networks, it depends on how you do it. Typically, this can actually make your protocol _worse_. If you check against a uniswap pool for example, maybe the pool is in the middle of a flashloan, and if your protocol goes "woah, the data is way different from Uniswap!" and acts because of it, you've actually opened up an attack vector!

If Chainlink is _stale_, then you can use a backup. But I wouldn't "sanity check" the fresh prices against a weaker oracle, especially an on-chain oracle. 

> Wait for validation if price is correct

This is why the Chainlink network is so powerful, you are already getting validation from a network of Chainlink nodes! 

> Fallback e.g falling back to the Tellor ETH:USD oracle under the following (extreme) conditions (no access 3~ 4h to chainlink oracle)

I think a fallback is ok only in the examples described above, if Chainlink prices are stale. There is an easy way to check for that. I do not recommend doing sanity checks. Tellor is one I usually don't recommend, there are scenarios where an attacker only has to risk very little [to gain a lot.](https://rekt.news/bonq-rekt/)

> Maybe some ML to predict anomaly/analyzing fluctuation/analyzing and forecasting based on chainlink historical price data

Yes! Chainlink nodes can do this already if they choose to! 

> do not assume chainlink is always correct (e.g multisig can be compromised)

Most protocols can add monitoring to check if the multi-sig becomes malicious, transparency is an awesome thing. The multi-sig is a temp measure as the network grows. A network as important as Chainlink needs a little hand holding time and again. 

> 4h, Maximum time period allowed since Chainlink's latest round data timestamp, beyond which Chainlink is considered frozen.

Yes, you should do this. 

> 50%, // Maximum deviation allowed between two consecutive Chainlink oracle prices. 18-digit precision.

Actually, I don't love this. We've seen times when prices _actually_ go crazy. So if you build a system that prevents crazy market conditions, you might be in trouble! 

> The last good price seen from an oracle by Liquity.

This is ok.

> fallback to tellor oracle

If that's what they please

> Your thoughts on whether these practices are worth implementing would be highly valuable

100%. I think using a fallback in times when Chainlink is stale is a great security recommendation. Uniswap TWAP oracles are ones that I usually recommend as a fallback, since they are more resistant to being manipulated, at the cost of being a little less accurate.
