### ISSUE TITLE
abstract contract

### ISSUE THREAD

**Issue by JhiNResH** [Cyfrin/foundry-defi-stablecoin-f23#48]
I found there's some version compatible problem and it keeps showing that 
if I wan to use ```pragma solidity ^0.8.19;```

Iit recommend to use 
```
abstract contract DecentralizedStableCoin is ERC20Burnable, Ownable{}
```
to run.
and it works.

I do not know what's the big difference, and why it should write it in this way in 0.8.20 while in 0.8.19 is
```contract DecentralizedStableCoin is ERC20Burnable, Ownable{}```

**Comment by JhiNResH** [comment]
I found out that in Solidity 0.8.20,  this behavior was changed, and a contract that does not implement all of the functions it inherits must be marked as an abstract contract.

Solidity 0.8.19, a contract could inherit from other contracts without implementing all of their functions and still be instantiated.

**Comment by Al-Qa-qa** [comment]
This is because of the new implementation of the OpenZeppelin contracts.

OpenZeppelin made some of their contract `abstract`, which means you must implement these contract functions and constructors if exist.

In the [Ownable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol) contract in OpenZeppelin, you will find that it is marked as `abstract`, and you will find that the constructor takes one argument, so you must provide this argument to the `Ownable` constructor in order to inherit it by a normal contract.

### Solution

In the `DecentralizedStableCoin.sol` add the Ownable constructor like this:
```solidity
constructor() ERC20("DecentralizedStableCoin", "DSC") Ownable(msg.sender) {}
```
### Note
Abstract contracts can't be deployed to the blockchain as it is, normal contracts are only allowed, and if the normal contract implements an abstract contract, then it will be deployed with it.

**Comment by JhiNResH** [comment]
Thanks a lot. This works!!
